package ExceptionHandling;

public class Example_3 
{
public static void main(String[] args)
{
	int a=100;
	int b=0;

try
{
	int div=a/b;
}
catch(ArithmeticException d)
{
	System.out.println("Show the Output Infinity");
}
{
	System.out.println("Done");
	}
}
}
